<html>
    <script type="text/javascript" src="<?php echo $this->baseUrl() . "/common/js/jquery-ui-1.8.20.custom.min.js"; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() . '/common/js/jquery-1.7.2.min.js'; ?>"></script>
    <head>
        <meta type="content" charset="utf-8" >
        <title>Car Rent Booking System </title>
        <?php
        echo $this->headLink()->appendStylesheet($this->baseUrl() . "/booking/admin/css/style.css");
        ?>
        <script type="text/javascript">
            site = {
                'baseUrl':"<?php echo $this->baseUrl(); ?>"
            };
        </script>
    </head>
    <body>
        <div id="top-navigation">
            <div id="header-nav">
                <ul id="menu-nav">       

                </ul>
            </div>
        </div>
        <div class='clear'></div>
        <div id="container">

            <div>
                <?php echo $this->layout()->content; ?>
            </div><div class='clear'></div>
        </div>
        <div id="footer-wrapper">
            <div id="footer-nav">

            </div>
        </div>
    </body>
</html>
